"""Initial migration

Revision ID: cd57d60c9eaf
Revises: 
Create Date: 2025-02-01 19:18:46.763809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd57d60c9eaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('tweets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tweets', sa.Column('received_at', sa.DateTime(), nullable=False))
    op.add_column('tweets', sa.Column('sent_by_user', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    op.drop_column('tweets', 'user')
    op.drop_column('users', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'sent_by_user')
    op.drop_column('tweets', 'received_at')
    op.drop_column('tweets', 'created_at')
    op.drop_column('tweets', 'user_id')
    # ### end Alembic commands ###
